
export const GLOBAL_SERVER_UPLOAD_CONFIG = {
  CHUNK_SIZE: 5 * 1024 * 1024,
  TOKEN_EXPIRATION: 300,
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 1000,
  RETRY_MULTIPLIER: 2,
  SMALL_CONCURRENT_UPLOADS: 5,
  MEDIUM_CONCURRENT_UPLOADS: 5,
  LARGE_CONCURRENT_UPLOADS: 5,
  PRESIGN_EXPIRY_SECONDS: 900,
  BUCKET: process.env.R2_BUCKET || 'gemif-web-main',
  WORKER_BASE_URL: process.env.NEXT_PUBLIC_WORKER_BASE_URL,
} as const;


export const FILE_SIZE_THRESHOLDS = {
  SMALL: 5 * 1024 * 1024,    // 5 MB
  MEDIUM: 50 * 1024 * 1024,  // 50 MB
  CHUNK: 5 * 1024 * 1024,    // 5 MB chunks for multipart
} as const;
