
export const S3_SERVER_UPLOAD_CONFIG = {
  TOKEN_EXPIRATION: 300,
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 1000,
  RETRY_MULTIPLIER: 2,
  CONCURRENT_UPLOADS: 5,
  PRESIGN_EXPIRY_SECONDS: 900,
  BUCKET: process.env.R2_BUCKET || 'gemif-web-main',
  WORKER_BASE_URL: process.env.NEXT_PUBLIC_WORKER_BASE_URL,
} as const;