
export const GLOBAL_CLIENT_UPLOAD_CONFIG = {
  SMALL_THRESHOLD: 5 * 1024 * 1024,
  LARGE_THRESHOLD: 50 * 1024 * 1024,
  CHUNK_SIZE: 5 * 1024 * 1024,
  MAX_BROWSER_CONNECTIONS: 6,
  SMALL_CONCURRENT_UPLOADS: 3,
  MEDIUM_CONCURRENT_UPLOADS: 2,
  LARGE_CONCURRENT_UPLOADS: 1,
  CHUNK_CONCURRENCY: 4,
  MAX_RETRIES: 2,
  RETRY_DELAY_MS: 1000,
  RETRY_MULTIPLIER: 2,
} as const;


// Constants optimized for browser limitations
const UPLOAD_CONSTANTS = {
  
} as const;

